Refactored release notes steps for use in release process too

diff --git a/.github/actions/release-notes-create/action.yml b/.github/actions/release-notes-create/action.yml
--- a/.github/actions/release-notes-create/action.yml
+++ b/.github/actions/release-notes-create/action.yml
@@ -19,41 +19,24 @@ runs:
 
   steps:
 
-    - name: Check and Seed Release Notes File
-      id: generate-version-release-notes
-      shell: bash
-      run: |
-        FILE="releases/v${{ inputs.version }}.md"
-        if [[ -f "$FILE" ]]; then
-          echo "created=false" >> $GITHUB_OUTPUT
-          echo "::notice title=Release Notes File Exists::$FILE"
-        else
-          mkdir -p releases
-          {
-            echo "# Release v${{ inputs.version }}"
-            echo ""
-            echo "## ✨ What's New"
-            echo ""
-            echo "- TBD"
-            echo ""
-            echo "## 🐛 Bug Fixes"
-            echo ""
-            echo "- TBD"
-            echo ""
-            echo "## 🔬 Internal"
-            echo ""
-            echo "- TBD"
-            echo ""
-            echo ""
-            echo "---"
-            echo ""
-            echo "## Logs"
-            echo ""
-            echo ""
-            echo "## Files"
-            echo ""
-            echo ""
-          } > "$FILE"
-          echo "created=true" >> $GITHUB_OUTPUT
-          echo "::notice title=Release Notes File Seeded::$FILE"
+  - name: Check and Seed Release Notes File
+    id: generate-version-release-notes
+    shell: bash
+    run: |
+      FILE="releases/v${{ inputs.version }}.md"
+      TEMPLATE=".github/templates/release-notes-template.md"
+      
+      if [[ -f "$FILE" ]]; then
+        echo "created=false" >> $GITHUB_OUTPUT
+        echo "::notice title=Release Notes File Exists::$FILE"
+      else
+        mkdir -p releases
+        if [[ ! -f "$TEMPLATE" ]]; then
+          echo "::error title=Missing Template::Expected template file $TEMPLATE"
+          exit 3
         fi
+      
+        sed "s/VERSION_TAG/v${{ inputs.version }}/g" "$TEMPLATE" > "$FILE"
+        echo "created=true" >> $GITHUB_OUTPUT
+        echo "::notice title=Release Notes File Seeded::$FILE"
+      fi
